### ISSUE TITLE
IsZero() method relies on exported variable

### ISSUE THREAD

**Issue by hweidner** [lukechampine/uint128#13]
In the current implementation, the IsZero() method relies on the variable Zero. But Zero is an exported variable which could, in theory, be altered by code from another package. This would break IsZero() and other methods which rely on IsZero(), e.g. String().

I'd recommend to rewrite IsZero() in a way that does not depend on Zero, e.g.

```
func (u Uint128) IsZero() bool {
	return u == Uint128{}
}
```

**Comment by lukechampine** [comment]
Good call, thanks!

It might be best to just remove the `Zero` variable, but that would be a breaking API change, so I'd have to be really sure about it.
