### ISSUE TITLE
Add fromString method

### ISSUE THREAD

**Issue by PaulAtFlexa** [lukechampine/uint128#17]
I would love to use this for uuid parsing.  Being able to go to base10 strings is great, but without a way to go back I can't use this.

Right now I do the following:

uuid str -> hex bytes -> u128 -> base 10 str

But I'm unable to reverse it as there's no way to get to u128 from the string.

**Comment by lukechampine** [comment]
Ok, I'll look into adding this.

In the meantime, you can do:
```go
func ParseUint128(s string) uint128.Uint128 {
	i, _ := new(big.Int).SetString(s, 10)
	return uint128.FromBig(i)
}
```
but be aware that this will panic on invalid inputs.

**Comment by lukechampine** [comment]
Added in https://github.com/lukechampine/uint128/commit/526fdb2b493c3e76d9310359d394cff779e4d70f. You can now do:
```go
u, err := uint128.FromString("123")
```
or use `fmt`:
```go
var u uint128.Uint128
fmt.Sscan("123", &u)
```

**Comment by PaulAtFlexa** [comment]
Thanks so much for the quick turnaround!  Appreciate it immensely :)

**Comment by dylan1951** [comment]
This doesn't work.

`can't scan type: *uint128.Uint128`

**Comment by lukechampine** [comment]
Can you post your code? Here's a working example: https://play.golang.com/p/Zx0Fj6ZmIX5

**Comment by dylan1951** [comment]
Hey thanks for your quick reply, turns out I was just being stupid. I forgot I modified the package slightly and I must've accidentally deleted uint128.Scan() lol.

**Comment by lukechampine** [comment]
Happens to the best of us! 🫡
