### ISSUE TITLE
Implement more math/bits methods

### ISSUE THREAD

**Issue by lukechampine** [lukechampine/uint128#5]
Feel free to submit separate PRs for any of the following methods:

- `Len`
- `OnesCount`
- `Reverse`
- `ReverseBytes`
- `RotateLeft`
- `RotateRight`
- `TrailingZeros`

Tests are very much appreciated, but not strictly required.

**Comment by hemraj4545** [comment]
[Added the methods #6  ](https://github.com/lukechampine/uint128/pull/6)
